### ISSUE TITLE
Configuration support for opensubtitles credentials

### ISSUE THREAD

**Issue by chopeta** [pannal/Subliminal.bundle#17]
Can we have support for opensubtitles credentials like we currently have for Addicted.

Right now I am hacking the code every time I install a new version to have my credential used.

Editting file `Contents/Libraries/Shared/subliminal/providers/opensubtitles.py` and around line #100 edit the line:

```
response = checked(self.server.LogIn('my-username-here', 'my-password-here', 'eng', 'subliminal v%s' % __version__.split('-')[0]))
```

**Comment by Roelie** [comment]
What is the benefit of using a logged in session on OpenSubtitles instead of anonymous query?

**Comment by chopeta** [comment]
If you are a VIP download limit is increased to 1000 subs instead of 200.
http://www.opensubtitles.org/en/support#vip

You can check status here: http://www.opensubtitles.org/addons/show_my_ip.php
