### ISSUE TITLE
"Scan: include embedded subtitles (skip if existing)" not working

### ISSUE THREAD

**Issue by BlueToxic** [pannal/Subliminal.bundle#19]
This function doesn't seem to work. For me subtitles are downloaded even if an embedded is available.

Tested with version 1.1-rc1 on PMS 0.9.12.13 Debian.

**Comment by Fardilha** [comment]
Hi.
Just to add my "me too" on this issue.

I have both "Scan: include embedded subtitles (skip if existing)" and "Scan: include external subtitles (skip if existing)" selected but no luck.

I'm using PMS 0.9.12.13  on Mac OS 10.11 with Subliminal.bundle 1.1-RC1.

**Comment by pannal** [comment]
Is this the case for any video file with embedded subs? Can you post a mediainfo dump of one file please?

**Comment by BlueToxic** [comment]
I was unable to upload the txt-file so I'll just post the results as text. I only included the "Text" part to keep it short, I hope that's what you need.

Text
ID: 3
Format: UTF-8
Codec ID: S_TEXT/UTF8
Codec ID/Info: UTF-8 Plain Text
Language: English
Default : Yes
Forced: No

**Comment by pannal** [comment]
OK that should work, I initially thought the embedded sub was an undefined one. I'll look into it, thanks :)

**Comment by pannal** [comment]
Could you post your plex.agents.subliminal.log* files?

**Comment by BlueToxic** [comment]
http://pastebin.com/Asqv6A7G
Here is my latest log, it should only contain the scan of one episode with embedded subs.

**Comment by pannal** [comment]
OK, enzyme finds the embedded subtitle, but with language "und". It doesn't detect its language: "2015-10-02 21:03:02,845 (7fbe2bdb7700) :  DEBUG (logger:21) - subliminal.video: Found embedded subtitle set([<Language [und]>]) with enzyme"

Thanks, looking into it.

**Comment by pannal** [comment]
I'm considering updating enzyme to the current version. It may not fix that problem, though.

Would this new setting help you: "Treat unknown-language embedded subtitle as found"?

**Comment by BlueToxic** [comment]
Yeah it would help in most cases I guess. But I assume that would mean no subs in any language will be downloaded if an unknown is detected?

**Comment by pannal** [comment]
Correct. I may have to have a deeper look into why it doesn't detect its obvious language.

**Comment by BlueToxic** [comment]
I mainly use english subs and if subs are embedded they are usually english so that setting will be good enough for me for now.

**Comment by pannal** [comment]
Maybe switching from enzyme to pymediainfo (https://github.com/paltman-archive/pymediainfo/tree/master/pymediainfo) will fix a whole bunch of problems as it can parse any media file available - we currently only support MKV when using enzyme.

**Comment by pannal** [comment]
Please try https://github.com/pannal/Subliminal.bundle/releases/tag/1.1-rc2

**Comment by BlueToxic** [comment]
Works perfectly for me, thank you.
