### ISSUE TITLE
Please add pt-br Language

### ISSUE THREAD

**Issue by trunet** [pannal/Subliminal.bundle#6]
Thanks for the nice work upgrading from 0.8.0 to 1.0.1...

Could you provide one additional language please?

pt-br stands for "Português Brasil", it's different than "Portuguese" that is used in portugal.

**Comment by pannal** [comment]
Did you test adding pt-br to the Strings/en.json file? If that's the only thing needed, I'll be glad to do so.
Otherwise it may need updating the providers.

**Comment by trunet** [comment]
you need to add to the DefaultPrefs.json and Strings/en.json and that's it.

thanks...

**Comment by pannal** [comment]
Should be fixed by e371b99dcae1508201b7c2017c7678f097ef4e84
